/*
  This file is automatically generated when you
  add a package to your package.json and run yarn.
  Please do not edit manually.
*/

import '@sleeperhq/mini-core';
import 'react';
import 'react-native';
import 'react-native-svg';
import '@shopify/flash-list';
import 'he';
import 'moment-timezone';
import 'react-native-webview';
